package imat.events;

public enum NavigationRoute {
    CHECKOUT_CART,
    CHECKOUT_CUSTOMER_INFO,
    CHECKOUT_ORDER_CONFIRMATION,
    CHECKOUT_SHIPPING_INFO,
    HELP,
    PRODUCTS_CATEGORY,
    PRODUCTS_FAVORITE,
    PRODUCTS_SEARCH,
    RECEIPTS
}
